apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-kyverno
placementBindingDefaults:
  name: binding-generic
policyDefaults:
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: kyverno
  remediationAction: enforce
  severity: medium
  policySets:
    - kyverno-integration  
  standards:
    - generic
  placementRulePath:  
    - ../placementrule-default.yaml
policies:
- name: policy-disallow-deprecated-apis
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/kyverno/validate/openshift/disallow-deprecated-apis.yaml
- name: disallow-jenkins-pipeline-strategy
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/kyverno/validate/openshift/disallow-jenkins-pipeline-strategy.yaml
- name: policy-disallow-security-context-constraint-anyuid
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/kyverno/validate/openshift/disallow-security-context-constraint-anyuid.yaml
- name: disallow-self-provisioner-binding
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/kyverno/validate/openshift/disallow-self-provisioner-binding.yaml
- name: policy-kyverno-enforce-etcd-encryption
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/kyverno/validate/openshift/enforce-etcd-encryption.yaml
- name: policy-check-routes
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/kyverno/validate/openshift/check-routes.yaml
