apiVersion: v1
kind: ResourceQuota
metadata:
  name: sc-resource-limit
spec:
  hard:
    requests.storage: 10Gi
    value.storageclass.storage.k8s.io/requests.storage: 8Gi
    value.storageclass.storage.k8s.io/persistentvolumeclaims: 3
