apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials
  namespace: openshift-adp
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id={{ fromSecret "openshift-adp" "backup-bucket" "AWS_ACCESS_KEY_ID" | base64dec }}
    aws_secret_access_key={{ fromSecret "openshift-adp" "backup-bucket" "AWS_SECRET_ACCESS_KEY" | base64dec }}
