apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-generic-restore
placementBindingDefaults:
  name: binding-generic
policyDefaults:
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: policies
  # Use an existing placement rule 
  placement:
    placementPath: ../placement-example.yaml
  remediationAction: enforce
  severity: medium
  standards:
    - generic
policies:
- name: policy-multiclusterhub
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/mulitclusterhub/MultiClusterHub.yaml
  complianceType: "mustonlyhave"
- name: policy-configure-backup-dataprotectionresource
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/hub_backup_restore/dataprotectionresource.yaml  
- name: policy-configure-backup-restore
  complianceType: "mustonlyhave"
  categories:
    - setup
  controls: 
    - setup
  disabled: true
  manifests:
    - path: ../input/hub_backup_restore/cluster_v1beta1_restore.yaml
- name: policy-configure-backup-restore-passive
  complianceType: "mustonlyhave"
  categories:
    - setup
  controls: 
    - setup
  disabled: true
  manifests:
    - path: ../input/hub_backup_restore/cluster_v1beta1_restore_passive.yaml
- name: policy-configure-backup-restore-passive-sync
  complianceType: "mustonlyhave"
  categories:
    - setup
  controls: 
    - setup
  disabled: true
  manifests:
    - path: ../input/hub_backup_restore/cluster_v1beta1_restore_passive_sync.yaml
- name: policy-configure-backup-restore-passive-activate
  complianceType: "mustonlyhave"
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/hub_backup_restore/cluster_v1beta1_restore_passive_activate.yaml     
- name: policy-backup-restore-passive-activate-skip-all
  complianceType: "mustonlyhave"
  categories:
    - setup
  controls: 
    - setup
  disabled: true
  manifests:
    - path: ../input/hub_backup_restore/restore-acm-passive-sync-skip.yaml
