---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: snow
  namespace: pacman
spec:
  job_template_name: snow
  extra_vars:
    sn_severity: 3
    sn_priority: 3
    appName: pacman