---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-cert-manager-operator
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name:  Red Hat Certificate Manager Operator
  labels:
    openshift.io/cluster-monitoring: 'true'
  name: openshift-cert-manager-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-cert-manager-operator
  namespace: openshift-cert-manager-operator
spec:
  channel: tech-preview
  installPlanApproval: Automatic
  name: openshift-cert-manager-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
