---
# Commented out content is serving as example for you to add new content.
controller_inventories:
  - name: localhost
    description: inventory for localhost
    organization: Default
  - name: ACM Cluster Inventory
    description: Load inventory for ACM
    organization: Default
    variables:
      ansible_python_interpreter: { "/usr/bin/python3.8" }
  - name: Demo Inventory
    organization: Default
    description: AAP
...