---  
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: policies
  namespace: policies2
spec:
  argoServer:
    cluster: local-cluster
    argoNamespace: policies2
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: placement-example
    namespace: policies2
