---
apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials
  namespace: openshift-adp 
stringData:
  aws_access_key_id: '{{ fromSecret "openshift-cloud-credential-operator" "cloud-credential-operator-iam-ro-creds" "AWS_ACCESS_KEY_ID" | base64dec }}'
  aws_secret_access_key: '{{ fromSecret "openshift-cloud-credential-operator" "cloud-credential-operator-iam-ro-creds" "AWS_SECRET_ACCESS_KEY" | base64dec }}'
type: Opaque
