---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: aa2022-rhacm-placement
  namespace: policies
spec:
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
          - local-cluster