apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-configure-aapcontroller
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: automationcontroller.ansible.com/v1beta1
        kind: AutomationController
        metadata:
          name: aapcontroller
          namespace: ansible-automation-platform
        spec:
          create_preload_data: true
          route_tls_termination_mechanism: Edge
          garbage_collect_secrets: true
          ingress_type: Route
          image_pull_policy: IfNotPresent
          task_privileged: false
          projects_persistence: false
          replicas: 1
          admin_user: admin
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-configure-aapcontroller
  namespace: policies
placementRef:
  name: placement-policy-configure-aapcontroller
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: policy-configure-aap-controller
    apiGroup: policy.open-cluster-management.io
    kind: Policy

---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-configure-aapcontroller
  namespace: policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
          - local-cluster