apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-configure-automationhub
  namespace: policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-configure-automationhub
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: automationhub.ansible.com/v1beta1
                kind: AutomationHub
                metadata:
                  name: automationhub
                  namespace: ansible-automation-platform
                spec:
                  route_tls_termination_mechanism: Edge
                  ingress_type: Route
                  loadbalancer_port: 80
                  file_storage_size: 100Gi
                  image_pull_policy: IfNotPresent
                  web:
                    replicas: 1
                  file_storage_access_mode: ReadWriteOnce
                  content:
                    log_level: INFO
                    replicas: 2
                  postgres_storage_requirements:
                    limits:
                      storage: 50Gi
                    requests:
                      storage: 8Gi
                  api:
                    log_level: INFO
                    replicas: 1
                  postgres_resource_requirements:
                    limits:
                      cpu: 1000m
                      memory: 8Gi
                    requests:
                      cpu: 500m
                      memory: 2Gi
                  loadbalancer_protocol: http
                  resource_manager:
                    replicas: 1
                  storage_type: File
                  worker:
                    replicas: 2
          remediationAction: inform
          severity: low
  remediationAction: enforce
status:
  compliant: Compliant
  placement:
    - placementBinding: binding-policy-configure-automationhub
      placementRule: placement-policy-configure-automationhub
  status:
    - clustername: local-cluster
      clusternamespace: local-cluster
      compliant: Compliant
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-configure-automationhub
  namespace: policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
          - local-cluster
status:
  decisions:
    - clusterName: local-cluster
      clusterNamespace: local-cluster
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-configure-automationhub
  namespace: policies
placementRef:
  name: placement-policy-configure-automationhub
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: policy-configure-automationhub
    apiGroup: policy.open-cluster-management.io
    kind: Policy