---
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: managed-serviceaccount
  namespace: local-cluster
spec:
  installNamespace: open-cluster-management-managed-serviceaccount