apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-configure-multiclusterhub
  namespace: policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-configure-multiclusterhub
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.open-cluster-management.io/v1
                kind: MultiClusterHub
                metadata:
                  name: multiclusterhub
                  namespace: open-cluster-management
                spec:
                  installNamespace: open-cluster-management
                  availabilityConfig: High
                  enableClusterBackup: false
                  imagePullSecret: multiclusterhub-operator-pull-secret
                  ingress:
                    sslCiphers:
                      - ECDHE-ECDSA-AES256-GCM-SHA384
                      - ECDHE-RSA-AES256-GCM-SHA384
                      - ECDHE-ECDSA-AES128-GCM-SHA256
                      - ECDHE-RSA-AES128-GCM-SHA256
                  overrides:
                    components:
                      - enabled: true
                        name: multiclusterhub-repo
                      - enabled: true
                        name: search
                      - enabled: true
                        name: management-ingress
                      - enabled: true
                        name: console
                      - enabled: true
                        name: insights
                      - enabled: true
                        name: grc
                      - enabled: true
                        name: cluster-lifecycle
                      - enabled: true
                        name: volsync
                      - enabled: true
                        name: multicluster-engine
                      - enabled: true
                        name: cluster-proxy-addon
                      - enabled: true
                        name: cluster-backup
                      - enabled: true
                        name: managedserviceaccount-preview
                  separateCertificateManagement: false
          remediationAction: inform
          severity: low
  remediationAction: enforce
status:
  compliant: Compliant
  placement:
    - placementBinding: binding-policy-configure-multiclusterhub
      placementRule: placement-policy-configure-multiclusterhub
  status:
    - clustername: local-cluster
      clusternamespace: local-cluster
      compliant: Compliant
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-configure-multiclusterhub
  namespace: policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
          - local-cluster
status:
  decisions:
    - clusterName: local-cluster
      clusterNamespace: local-cluster
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-configure-multiclusterhub
  namespace: policies
placementRef:
  name: placement-policy-configure-multiclusterhub
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: policy-configure-multiclusterhub
    apiGroup: policy.open-cluster-management.io
    kind: Policy