apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-configure-subscription-admin-hub
  namespace: policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-configure-subscription-admin-hub
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRole
                metadata:
                  name: open-cluster-management:subscription-admin
                rules:
                  - apiGroups:
                      - app.k8s.io
                    resources:
                      - applications
                    verbs:
                      - "*"
                  - apiGroups:
                      - apps.open-cluster-management.io
                    resources:
                      - "*"
                    verbs:
                      - "*"
                  - apiGroups:
                      - ""
                    resources:
                      - configmaps
                      - secrets
                      - namespaces
                    verbs:
                      - "*"
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRoleBinding
                metadata:
                  name: open-cluster-management:subscription-admin
                roleRef:
                  name: open-cluster-management:subscription-admin
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                subjects:
                  - name: kube:admin
                    apiGroup: rbac.authorization.k8s.io
                    kind: User
                  - name: system:admin
                    apiGroup: rbac.authorization.k8s.io
                    kind: User
                  - name: opentlc-mgr
                    apiGroup: rbac.authorization.k8s.io
                    kind: User
          remediationAction: inform
          severity: low
  remediationAction: enforce
status:
  compliant: Compliant
  placement:
    - placementBinding: binding-policy-configure-subscription-admin-hub
      placementRule: placement-policy-configure-subscription-admin-hub
  status:
    - clustername: local-cluster
      clusternamespace: local-cluster
      compliant: Compliant
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-configure-subscription-admin-hub
  namespace: policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
          - local-cluster
status:
  decisions:
    - clusterName: local-cluster
      clusterNamespace: local-cluster
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-configure-subscription-admin-hub
  namespace: policies
placementRef:
  name: placement-policy-configure-subscription-admin-hub
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: policy-configure-subscription-admin-hub
    apiGroup: policy.open-cluster-management.io
    kind: Policy