apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mobile-application-set
  namespace: redteam
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: red-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: mobileapp-{{name}}
    spec:
      project: default
      source:
        repoURL: https://github.com/rokej/RedApplications.git
        targetRevision: main
        path: mobileApplication
      destination:
        namespace: mobileapp
        server: "{{server}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
