apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-generic
placementBindingDefaults:
  name: binding-generic
policyDefaults:
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: policies
  remediationAction: inform
  severity: medium
  standards:
    - generic 
  placement:
    placementRulePath: ../placementrule-default.yaml    
policies:
- name: policy-aap
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/ansible/aap-operator.yaml
- name: policy-automationhub
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/ansible/automation-hub.yaml
- name: policy-automationcontroller
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/ansible/controller.yaml    
- name: policy-submariner
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/configurations/submariner/submariner-templatized-aws.yaml
- name: policy-gitops
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/operators/gitopsoperator.yaml
- name: policy-argoapp
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/gitops
- name: policy-addon-managed-service-account
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/mulitclusterhub/managed-serviceaccount.yaml
- name: policy-multiclusterhub
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/mulitclusterhub/MultiClusterHub.yaml
  complianceType: "mustonlyhave"
- name: policy-configure-backup-dataprotectionresource
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/hub_backup_restore/dataprotectionresource.yaml
- name: policy-configure-backup-backup-schedule
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/hub_backup_restore/backup-schedule.yaml
