# apply this resource to restore hub resources in a passive configuration
# restored managed clusters will show as detached on the current hub, where this resource is applied

# cleanupBeforeRestore - required, asks to clean up cluster before applying restore
# valid options : 
# CleanupRestored - clean up only resources created by a previous acm restore
# CleanupAll - clean up all resources defined by the acm backups IncludedResources spec
#              even if they were not created as a result of a restore operation
#              Use this option with caution as this could cleanup resources on the hub
#              created by the user, that should be kept even if they are not in the restored resources

# None : don't clean up anything, just apply the restore


apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Restore
metadata:
  name: restore-acm-passive
  namespace: open-cluster-management-backup
spec:
  cleanupBeforeRestore: CleanupRestored
  veleroManagedClustersBackupName: skip
  veleroCredentialsBackupName: latest
  veleroResourcesBackupName: latest
