---  
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: redargocd
  namespace: redargocd
spec:
  argoServer:
    cluster: local-cluster
    argoNamespace: redargocd
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: redargocd
    namespace: redargocd
