apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-configure-managed-serviceaccount
  namespace: policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: addon.open-cluster-management.io/v1alpha1
        kind: ManagedClusterAddOn
        metadata:
          name: managed-serviceaccount
          namespace: local-cluster
        spec:
          installNamespace: open-cluster-management-managed-serviceaccount
          remediationAction: inform
          severity: low
  remediationAction: enforce
#---
#apiVersion: apps.open-cluster-management.io/v1
#kind: PlacementRule
#metadata:
#  name: placement-policy-configure-managed-serviceaccount
#  namespace: policies
#spec:
#  clusterConditions:
#    - status: "True"
#      type: ManagedClusterConditionAvailable
#  clusterSelector:
#    matchExpressions:
#      - key: name
#        operator: In
#        values: raghu-kind
#          -
#---
#apiVersion: policy.open-cluster-management.io/v1
#kind: PlacementBinding
#metadata:
#  name: binding-policy-configure-managed-serviceaccount
#  namespace: policies
#placementRef:
#  name: placement-policy-configure-managed-serviceaccount
#  apiGroup: apps.open-cluster-management.io
#  kind: PlacementRule
#subjects:
#  - name: policy-configure-managed-serviceaccount
#    apiGroup: policy.open-cluster-management.io
#    kind: Policy
---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: aa2022-managed-clusters
  namespace: policies
spec:
  description: ""
  policies:
    - policy-configure-managed-serviceaccount
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: aa2022-managed-clusters-placement
  namespace: policies
spec:
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
          - local-cluster
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: aa2022-managed-clusters-placement
  namespace: policies
placementRef:
  name: aa2022-managed-clusters-placement
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: aa2022-managed-clusters
    apiGroup: policy.open-cluster-management.io
    kind: PolicySet














