---
controller_hosts:
  - name: localhost
    inventory: localhost
    variables:
      ansible_connection: local
      ansible_python_interpreter:  "ansible_playbook_python"
  - name: local-cluster
    inventory: ACM Cluster Inventory
    variables:
      cluster_name:  "local-cluster"
...