---
controller_projects:
  - name: ACM Ansible Collection Demo
    scm_type: git
    scm_url: https://github.com/TheRealHaoLiu/acm-ansible-collection-demo
    scm_branch: master
    scm_clean: true
    description: ACM Ansible Collection Demo
    organization: Default
    wait: true
    update: true
  - name: Demo Project
    scm_type: git
    scm_url: https://github.com/ansible/ansible-tower-samples
    scm_branch: master
    scm_clean: true
    description: Demo Project
    organization: Default
    wait: true
    update: true
  - name: Rhoda
    scm_type: git
    scm_url: https://github.com/veniceofcode/rhoda
    description: DBAAS
    organization: Default
  - name: SNOW
    scm_type: git
    scm_url: https://github.com/levenhagen/ansible_snow
    description: Snow
    organization: Default
...
