---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: aa2022-rhacm
  name: aa2022-rhacm-placement-1
  namespace: policies
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'