apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-namespace-nist
placementBindingDefaults:
  name: binding-bsi-grundschutz
policyDefaults:
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: policies
  # Use an existing placement rule 
  placement:
    placementPath: ../placement-example.yaml
  remediationAction: enforce
  severity: medium
  standards:
    - BsiGrundschutz
policies:
- name: policy-submariner
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/configurations/submariner/submariner-templatized-aws.yaml
- name: policy-gitops
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/operators/gitopsoperator.yaml
- name: policy-argoapp
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/gitops
- name: policy-certmanagerfull
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/certmanager
- name: policy-addon-managed-service-account
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/mulitclusterhub/managed-serviceaccount.yaml
- name: policy-multiclusterhub
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/mulitclusterhub/MultiClusterHub.yaml
  complianceType: "mustonlyhave"
